### ISSUE TITLE
Add support for the new Cargo locking

### ISSUE THREAD

**Issue by Shnatsel** [EmbarkStudios/tame-index#42]
Cargo is splitting its global package lock into three, as described here: https://blog.rust-lang.org/2023/12/11/cargo-cache-cleaning.html

This is nightly-only for now, but will eventually ship on stable. `tame-index` will need to support this one way or another to avoid races with Cargo. I haven't looked in detail into what that will entail, exactly.

**Comment by Jake-Shadle** [comment]
From looking at the implementation, `tame-index` does not have to do anything. The `.package-cache` lock is still used for , and the new `.package-cache-mutate` is (confusingly due to the name) used to either provide exclusive or shared access to the unpacked sources in `registry/src/<index>` which isn't used by this crate. This can be reopened if that implementation changes, but the use of the same `.package-cache` lock indicates to me that this is intentionally done to be backwards compatible.
